---
- name: Testing andrewrothstein.sudoers
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Test `sudo true`
      ansible.builtin.command: sudo true
      changed_when: false
