---
- name: building
  hosts: all
  vars:
    upstream_registry: '{{ lookup("env", "UPSTREAM_REGISTRY") | default("quay.io", True) }}'
    upstream_slug: '{{ lookup("env", "UPSTREAM_GROUP") | default("andrewrothstein/docker-python3", True) }}'
    upstream_ver: 0.0.0
    target_registry: '{{ lookup("env", "TARGET_REGISTRY") | default("quay.io", True) }}'
    target_slug: '{{ lookup("env", "TARGET_SLUG") | default("andrewrothstein/ansible-sudoers", True) }}'
    target_ver: 0.0.0
    target_os: '{{ lookup("env", "OS") }}'
    target_os_ver: '{{ lookup("env", "VER") }}'
    ansible_bender:
      base_image: '{{ upstream_registry }}/{{ upstream_slug }}:{{ upstream_ver }}-{{ target_os }}-{{ target_os_ver }}'
      working_container:
        volumes:
          - '{{ playbook_dir }}:/src'
      target_image:
        name: '{{ target_registry }}/{{ target_slug }}:{{ target_ver }}-{{ target_os }}-{{ target_os_ver }}'
        working_dir: /src
        labels:
          built-by: andrewrothstein
  roles:
    - role: '{{ playbook_dir }}'
