---
- name: building
  hosts: all
  vars:
    upstream_registry: '{{ lookup("env", "UPSTREAM_REGISTRY") | default("ghcr.io", True) }}'
    upstream_slug: '{{ lookup("env", "UPSTREAM_SLUG") | default("andrewrothstein/docker-python3", True) }}'
    upstream_ver: '{{ lookup("env", "UPSTREAM_VER") | default("0.0.0", True) }}'
    target_registry: '{{ lookup("env", "TARGET_REGISTRY") | default("ghcr.io", True) }}'
    target_slug: '{{ lookup("env", "GITHUB_REPOSITORY") }}'
    target_ver: '{{ lookup("env", "TARGET_VER") | default("0.0.0", True) }}'
    target_os: '{{ lookup("env", "TARGET_OS") }}'
    target_os_ver: '{{ lookup("env", "TARGET_OS_VER") }}'
    ansible_bender:
      ansible_extra_args: "-vvv"
      base_image: '{{ upstream_registry }}/{{ upstream_slug }}:{{ upstream_ver }}-{{ target_os }}-{{ target_os_ver }}'
      working_container:
        volumes:
          - '{{ playbook_dir }}:/src'
      target_image:
        name: '{{ target_registry }}/{{ target_slug }}:{{ target_ver }}-{{ target_os }}-{{ target_os_ver }}'
        working_dir: /src
        labels:
          built-by: andrewrothstein
  roles:
    - role: '{{ playbook_dir }}'
