---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install task
      uses: andrewrothstein/setup-task@feature/nvm-and-fix-warnings
    - name: download task mono
      uses: actions/checkout@v2
      with:
        repository: andrewrothstein/tasks
        ref: develop
        path: taskmono
    - name: task ver
      run: task --version
    - name: 'task #ftw'
      run: |
        task \
          -t taskmono/tasks/ansible-test-role.yml \
          "alltags=${{ matrix.os }}"
    strategy:
      matrix:
        os:
        - alpine_3.16
        - alpine_3.17
        - alpine_edge
        - archlinux_latest
        - debian_bullseye
        - debian_buster
        - fedora_36
        - fedora_37
        - rockylinux_8
        - rockylinux_9
        - ubuntu_bionic
        - ubuntu_focal
        - ubuntu_jammy
        python-versions:
        - '3.9'
name: dcb
'on':
- push
